version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:13306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  streamset-dc:
    image: "streamsets/datacollector"
    container_name: dc
    ports:
     - "18630:18630"
     - "8000:8000"
    volumes:
     - ./sdc/data:/data
     - ./sdc/resources:/resources
     - ./input:/input

# Names our volume
volumes:
  my-db: