version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  

  streamset-dc:
    image: "streamsets/datacollector"
    container_name: dc
    ports:
     - "18630:18630"
     - "8000:8000"

    volumes:
     - ./sdc/data:/data
     - ./sdc/resources:/resources
     - ./input:/input

# Names our volume
volumes:
  my-db: